---
- name: Check if database already exists
  postgresql_db:
    name: "{{ odoo_db_name }}"
    state: present
    login_host: localhost
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    port: 5432
  register: db_exists
  ignore_errors: no
  check_mode: yes
  become: yes
  become_user: postgres

- name: Initialize Odoo database
  command: >
    {{ odoo_home_path }}/odoo-venv/bin/python3 {{ odoo_home_path }}/odoo/odoo-bin --no-http
    --stop-after-init
    -d {{ odoo_db_name }}
    -i base
    --db_host={{ postgres_host }}
    --without-demo=true
    --lang={{ odoo_lang }}
    --load-language={{ odoo_lang }}
    -c /etc/{{ odoo_user }}.conf
  args:
    chdir: "{{ odoo_home_path }}"
  register: init_result
  when: not db_exists.failed
  timeout: "{{ db_creation_timeout }}"
  become: yes
  become_user: "{{ odoo_user }}"